float:
  any:
  - base_args: ['@metric']
    constructor: GSann
    disabled: false
    docker_tag: ann-benchmarks-gsann
    module: ann_benchmarks.algorithms.gsann
    name: gsann
    run_groups:
      gsann0:
        args: [[0], [0.0], [0.0]]

      gsann1-60-10:
        args: [[1], [0.6], [0.1]]
      gsann1-80-10:
        args: [[1], [0.8], [0.1]]
      gsann1-95-10:
        args: [[1], [0.95], [0.1]]
      gsann1-80-30:
        args: [[1], [0.8], [0.3]]
      gsann1-80-50:
        args: [[1], [0.8], [0.5]]
      gsann1-80-70:
        args: [[1], [0.8], [0.7]]

      gsann2-60-10:
        args: [[2], [0.6], [0.1]]
      gsann2-80-10:
        args: [[2], [0.8], [0.1]]
      gsann2-95-10:
        args: [[2], [0.95], [0.1]]
      gsann2-80-30:
        args: [[2], [0.8], [0.3]]
      gsann2-80-50:
        args: [[2], [0.8], [0.5]]
      gsann2-80-70:
        args: [[2], [0.8], [0.7]]

      gsann3-60-10:
        args: [[3], [0.6], [0.1]]
      gsann3-80-10:
        args: [[3], [0.8], [0.1]]
      gsann3-95-10:
        args: [[3], [0.95], [0.1]]
      gsann3-80-30:
        args: [[3], [0.8], [0.3]]
      gsann3-80-50:
        args: [[3], [0.8], [0.5]]
      gsann3-80-70:
        args: [[3], [0.8], [0.7]]

      gsann4-60-10:
        args: [[4], [0.6], [0.1]]
      gsann4-80-10:
        args: [[4], [0.8], [0.1]]
      gsann4-95-10:
        args: [[4], [0.95], [0.1]]
      gsann4-80-30:
        args: [[4], [0.8], [0.3]]
      gsann4-80-50:
        args: [[4], [0.8], [0.5]]
      gsann4-80-70:
        args: [[4], [0.8], [0.7]]
