float:
  any:
  - base_args: ['@metric']
    constructor: GSann
    disabled: false
    docker_tag: ann-benchmarks-gsann
    module: ann_benchmarks.algorithms.gsann
    name: gsann
    run_groups:
      gsann-80-10:
        args: [[1], [1.0], [1.0]]
